# Generated by Django 3.2.6 on 2022-05-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuinfos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='coursestudent',
        ),
        migrations.DeleteModel(
            name='stu',
        ),
    ]
