# Generated by Django 3.2.6 on 2022-05-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuinfos', '0005_course_coursestudent_stu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudent',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='stu_id',
        ),
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='coursestudent',
        ),
        migrations.DeleteModel(
            name='stu',
        ),
    ]
