# Generated by Django 3.2.6 on 2022-05-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuinfos', '0017_auto_20220524_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='stuID',
            field=models.IntegerField(),
        ),
    ]
